<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { ElMessageBox } from 'element-plus'
import { getWorkflowVersion, listWorkflowVersions, publishWorkflow, runWorkflow, updateWorkflow, validateWorkflow,
  type Workflow, type WorkflowDraft, type WorkflowEdge, type WorkflowNode, type WorkflowVersion } from '@/api/workflows'
import { notifySuccess } from '@/utils/notify'

const props=defineProps<{modelValue:boolean;workflow?:Workflow}>()
const emit=defineEmits<{(e:'update:modelValue',value:boolean):void;(e:'saved'):void}>()
const draft=ref<WorkflowDraft>({name:'',description:'',schemaVersion:1,nodes:[],edges:[]})
const selected=ref('');const connecting=ref('');const busy=ref(false);const versions=ref<WorkflowVersion[]>([]);const diffVisible=ref(false);const publishedJson=ref('')
watch(()=>props.workflow,(value)=>{if(!value)return;draft.value=JSON.parse(JSON.stringify({name:value.name,description:value.description,schemaVersion:value.schemaVersion,nodes:value.nodes,edges:value.edges})) as WorkflowDraft;layoutMissing();selected.value=value.nodes[0]?.nodeKey??''},{immediate:true})
const selectedNode=computed(()=>draft.value.nodes.find(node=>node.nodeKey===selected.value))
const draftJson=computed(()=>JSON.stringify(draft.value,null,2))
function pos(node:WorkflowNode,index:number){const ui=(node.config.__ui??{}) as {x?:number;y?:number};return{x:ui.x??80+(index%4)*210,y:ui.y??70+Math.floor(index/4)*150}}
function layoutMissing(){draft.value.nodes.forEach((node,index)=>{if(!node.config.__ui)node.config.__ui=pos(node,index)})}
function add(type:string){const key=`${type.toLowerCase()}_${Date.now().toString(36)}`;const defaults:Record<string,Record<string,unknown>>={START:{},TEMPLATE:{template:'{{start.userMessage}}',outputVariable:'answer'},CONDITION:{expression:'{{start.userMessage}} contains keyword',outputVariable:'matched'},KNOWLEDGE:{knowledgeBaseId:'',query:'{{start.userMessage}}',topK:5,outputVariable:'knowledge'},END:{output:'{{template.answer}}'}};draft.value.nodes.push({nodeKey:key,type,name:type,config:{...defaults[type],__ui:{x:100+draft.value.nodes.length*35,y:80+draft.value.nodes.length*28}}});selected.value=key}
function removeNode(){if(!selected.value)return;draft.value.nodes=draft.value.nodes.filter(n=>n.nodeKey!==selected.value);draft.value.edges=draft.value.edges.filter(e=>e.sourceNodeKey!==selected.value&&e.targetNodeKey!==selected.value);selected.value=''}
function clickNode(key:string){if(connecting.value&&connecting.value!==key){draft.value.edges.push({edgeKey:`edge_${Date.now().toString(36)}`,sourceNodeKey:connecting.value,targetNodeKey:key,defaultBranch:false});connecting.value=''}selected.value=key}
function beginConnect(){if(selected.value)connecting.value=selected.value}
function onDrag(event:DragEvent,node:WorkflowNode){event.dataTransfer?.setData('node-key',node.nodeKey)}
function onDrop(event:DragEvent){const key=event.dataTransfer?.getData('node-key');const node=draft.value.nodes.find(n=>n.nodeKey===key);const box=(event.currentTarget as HTMLElement).getBoundingClientRect();if(node)node.config.__ui={x:Math.max(10,event.clientX-box.left-70),y:Math.max(10,event.clientY-box.top-28)}}
function edgePath(edge:WorkflowEdge){const a=draft.value.nodes.findIndex(n=>n.nodeKey===edge.sourceNodeKey),b=draft.value.nodes.findIndex(n=>n.nodeKey===edge.targetNodeKey);const p1=pos(draft.value.nodes[a],a),p2=pos(draft.value.nodes[b],b);return`M ${p1.x+140} ${p1.y+28} C ${p1.x+175} ${p1.y+28}, ${p2.x-35} ${p2.y+28}, ${p2.x} ${p2.y+28}`}
function updateConfig(value:string){if(!selectedNode.value)return;try{selectedNode.value.config=JSON.parse(value)}catch{/* server validation remains authoritative */}}
async function save(){if(!props.workflow)return;busy.value=true;try{await updateWorkflow(props.workflow.id,draft.value);await validateWorkflow(props.workflow.id);notifySuccess('草稿已保存并通过图校验');emit('saved')}finally{busy.value=false}}
async function publish(){if(!props.workflow)return;await save();const version=await publishWorkflow(props.workflow.id);notifySuccess(`Workflow v${version.versionNo} 已发布`);emit('saved')}
async function dryRun(){if(!props.workflow?.publishedVersionId){await ElMessageBox.alert('请先发布版本','无法试跑');return}const {value}=await ElMessageBox.prompt('输入 userMessage','试跑已发布版本',{inputValue:'我想申请退款'});const result=await runWorkflow(props.workflow.publishedVersionId,value);await ElMessageBox.alert(`${result.output??result.errorMessage}\n\n${result.nodes.length} nodes · ${result.elapsedMs??0} ms`,result.status)}
async function openDiff(){if(!props.workflow)return;versions.value=await listWorkflowVersions(props.workflow.id);const latest=versions.value[0];publishedJson.value=latest?JSON.stringify(await getWorkflowVersion(latest.id),null,2):'尚无发布版本';diffVisible.value=true}
</script>

<template><el-drawer :model-value="modelValue" size="94%" direction="rtl" destroy-on-close @update:model-value="emit('update:modelValue',$event)"><template #header><div class="canvas-head"><div><b>{{draft.name}}</b><small>确定性 Workflow 画布 · 草稿与 Runtime 共用同一 DSL</small></div><div><el-button @click="openDiff">版本 Diff</el-button><el-button @click="dryRun">试跑</el-button><el-button :loading="busy" @click="save">保存并校验</el-button><el-button type="primary" class="primary-gradient" @click="publish">发布</el-button></div></div></template><div class="designer"><aside class="palette"><h4>节点面板</h4><el-button v-for="type in ['START','TEMPLATE','CONDITION','KNOWLEDGE','END']" :key="type" plain @click="add(type)">＋ {{type}}</el-button><p>选中节点后点“连接”，再点目标节点。节点可拖动。</p></aside><main class="surface" @dragover.prevent @drop="onDrop"><svg><path v-for="edge in draft.edges" :key="edge.edgeKey" :d="edgePath(edge)"/></svg><div v-for="(node,index) in draft.nodes" :key="node.nodeKey" draggable="true" class="node" :class="{active:selected===node.nodeKey,connecting:connecting===node.nodeKey}" :style="{left:pos(node,index).x+'px',top:pos(node,index).y+'px'}" @dragstart="onDrag($event,node)" @click="clickNode(node.nodeKey)"><span>{{node.type}}</span><b>{{node.name}}</b><small>{{node.nodeKey}}</small></div></main><aside class="props"><h4>属性面板</h4><template v-if="selectedNode"><el-form label-position="top"><el-form-item label="名称"><el-input v-model="selectedNode.name"/></el-form-item><el-form-item label="Node Key"><el-input :model-value="selectedNode.nodeKey" disabled/></el-form-item><el-form-item label="Config JSON"><el-input :model-value="JSON.stringify(selectedNode.config,null,2)" type="textarea" :rows="13" @change="updateConfig"/></el-form-item></el-form><el-button type="primary" plain @click="beginConnect">{{connecting?'请选择目标节点':'连接到…'}}</el-button><el-button type="danger" plain @click="removeNode">删除节点</el-button><h4>连线</h4><div v-for="edge in draft.edges" :key="edge.edgeKey" class="edge-row"><span>{{edge.sourceNodeKey}} → {{edge.targetNodeKey}}</span><el-button link type="danger" @click="draft.edges=draft.edges.filter(e=>e!==edge)">删除</el-button></div></template><el-empty v-else description="选择一个节点" :image-size="64"/></aside></div><el-dialog v-model="diffVisible" title="草稿 / 最新发布版本" width="88%" append-to-body><div class="diff"><section><h4>当前草稿</h4><pre>{{draftJson}}</pre></section><section><h4>最新发布快照</h4><pre>{{publishedJson}}</pre></section></div></el-dialog></el-drawer></template>

<style scoped>.canvas-head{display:flex;align-items:center;justify-content:space-between;width:100%;gap:20px}.canvas-head small{display:block;margin-top:4px;color:var(--color-text-tertiary)}.designer{display:grid;grid-template-columns:170px minmax(600px,1fr) 300px;height:calc(100vh - 105px);gap:14px}.palette,.props{padding:16px;background:var(--color-bg-secondary);border:1px solid var(--color-border);border-radius:var(--radius-lg);overflow:auto}.palette .el-button{width:100%;margin:0 0 9px}.palette p{font-size:12px;line-height:1.6;color:var(--color-text-tertiary)}.surface{position:relative;overflow:auto;min-height:620px;background-color:#f8faff;background-image:radial-gradient(#cfd7ef 1px,transparent 1px);background-size:20px 20px;border:1px solid var(--color-border);border-radius:var(--radius-lg)}svg{position:absolute;inset:0;width:1400px;height:900px;pointer-events:none}path{fill:none;stroke:#8b5cf6;stroke-width:2}.node{position:absolute;display:flex;flex-direction:column;width:140px;min-height:56px;padding:10px 12px;background:#fff;border:1px solid #dce2f2;border-radius:10px;box-shadow:0 8px 20px rgba(37,48,85,.09);cursor:grab}.node span{font-size:10px;font-weight:800;color:#6d5ce7}.node small{margin-top:4px;color:#8a94a8}.node.active{border-color:#6d5ce7;box-shadow:0 0 0 3px rgba(109,92,231,.14)}.node.connecting{border-color:#10b981}.edge-row{display:flex;justify-content:space-between;align-items:center;font-size:12px}.diff{display:grid;grid-template-columns:1fr 1fr;gap:16px}.diff pre{height:55vh;overflow:auto;padding:14px;color:#cfe3ff;background:#101624;border-radius:10px;font-size:11px}@media(max-width:1050px){.designer{grid-template-columns:130px minmax(520px,1fr) 250px}}</style>
