#!/usr/bin/env python3
"""Render the human API inventory from its reviewed contract; --check catches drift."""
import argparse
import json
from pathlib import Path


def render(root: Path) -> str:
    manifest = json.loads((root / "docs/spec/http-api.json").read_text())
    endpoints = manifest["endpoints"]
    lines = ["<!-- GENERATED by harness/render-api-spec.py; edit http-api.json instead. -->",
             "# HTTP 接口测试规格", "",
             f"共 {len(endpoints)} 个显式应用接口。Spring 路由双向校验：`ApiContractInventoryTest`。",
             "库存完整不等于行为已验证；候选测试仅为审查入口，执行结果见本轮 evidence。",
             "请求/响应 DTO 的完整字段与约束见对应 Controller 引用的 Java 类型；通用语义见 [README](README.md)。",
             "不包含框架 `/error`、运维 `/actuator` 与隐式 HEAD/OPTIONS。", ""]
    for feature in sorted({item["feature"] for item in endpoints}):
        lines += [f"## {feature}", ""]
        for item in (x for x in endpoints if x["feature"] == feature):
            lines += [f"### {item['method']} {item['path']}", "",
                      f"- 功能：{item['purpose']}。",
                      f"- 输入：`{item['request']}`。",
                      f"- 成功：HTTP {item['success']}，`{item['response']}`。",
                      f"- 必测断言/边界：{item['checks']}。",
                      f"- 实现：[{item['handler']}](../../{item['source']})。",
                      "- 候选测试（非逐接口覆盖承诺）：" + ("；".join(
                          f"[{Path(t).stem}](../../{t})" for t in item["testCandidates"])
                          or "尚无专用行为测试，需要补齐") + "。", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    target = root / "docs/spec/HTTP_API.md"
    content = render(root)
    if args.check:
        if not target.exists() or target.read_text() != content:
            print("API spec out of date; run python3 harness/render-api-spec.py")
            return 1
        print("Generated API spec is current")
    else:
        target.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
