package com.hify.mcp.application;
import com.fasterxml.jackson.databind.*; import com.fasterxml.jackson.databind.node.*; import com.hify.common.*; import com.hify.mcp.domain.McpServer; import org.springframework.stereotype.Component; import java.net.*; import java.net.http.*; import java.nio.charset.StandardCharsets; import java.time.Duration; import java.util.*;
@Component
public class McpProtocolClient {
 private static final String PROTOCOL="2025-06-18"; private final ObjectMapper json; private final McpEndpointGuard guard; private final McpCredentialResolver credentials; private final HttpClient http;
 public McpProtocolClient(ObjectMapper json,McpEndpointGuard guard,McpCredentialResolver credentials){this.json=json;this.guard=guard;this.credentials=credentials;this.http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5)).followRedirects(HttpClient.Redirect.NEVER).build();}
 public List<RemoteTool> listTools(McpServer server){Session s=initialize(server);JsonNode result=exchange(server,s,"tools/list",json.createObjectNode()).path("result");if(!result.path("tools").isArray())throw new BizException(ErrorCode.CONFLICT,"MCP tools/list returned no tools array");List<RemoteTool> tools=new ArrayList<>();for(JsonNode t:result.path("tools")){String name=t.path("name").asText();if(name.isBlank())throw new BizException(ErrorCode.CONFLICT,"MCP tool name is missing");JsonNode schema=t.path("inputSchema");if(!schema.isObject())throw new BizException(ErrorCode.CONFLICT,"MCP tool inputSchema is missing");boolean readOnly=t.path("annotations").path("readOnlyHint").asBoolean(false);tools.add(new RemoteTool(name,t.path("description").asText(""),schema,readOnly?"READ":"EXTERNAL"));}return tools;}
 public CallResult call(McpServer server,String toolName,JsonNode arguments){Session s=initialize(server);ObjectNode p=json.createObjectNode();p.put("name",toolName);p.set("arguments",arguments==null?json.createObjectNode():arguments);JsonNode result=exchange(server,s,"tools/call",p).path("result");return new CallResult(result,result.path("isError").asBoolean(false));}
 private Session initialize(McpServer server){ObjectNode p=json.createObjectNode();p.put("protocolVersion",PROTOCOL);p.set("capabilities",json.createObjectNode());ObjectNode info=p.putObject("clientInfo");info.put("name","hify");info.put("version","0.1.0");Exchange init=post(server,null,"initialize",p);String protocol=init.body().path("result").path("protocolVersion").asText();if(protocol.isBlank())throw new BizException(ErrorCode.CONFLICT,"MCP initialize response is invalid");Session session=new Session(init.sessionId());notifyInitialized(server,session);return session;}
 private JsonNode exchange(McpServer server,Session session,String method,JsonNode params){return post(server,session,method,params).body();}
 private Exchange post(McpServer server,Session session,String method,JsonNode params){
  try{URI uri=guard.validate(server.getEndpointUrl());ObjectNode rpc=json.createObjectNode();rpc.put("jsonrpc","2.0");rpc.put("id",UUID.randomUUID().toString());rpc.put("method",method);rpc.set("params",params);HttpRequest.Builder b=HttpRequest.newBuilder(uri).timeout(Duration.ofSeconds(30)).header("Content-Type","application/json").header("Accept","application/json, text/event-stream").header("MCP-Protocol-Version",PROTOCOL).POST(HttpRequest.BodyPublishers.ofString(json.writeValueAsString(rpc),StandardCharsets.UTF_8));if(session!=null&&session.id()!=null)b.header("Mcp-Session-Id",session.id());String secret=credentials.resolve(server.getCredentialRef());if(secret!=null)b.header("Authorization","Bearer "+secret);HttpResponse<String> response=http.send(b.build(),HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));if(response.statusCode()/100!=2)throw new BizException(ErrorCode.CONFLICT,"MCP server returned HTTP "+response.statusCode());JsonNode body=parse(response);if(body.has("error"))throw new BizException(ErrorCode.CONFLICT,"MCP error: "+body.path("error").path("message").asText("unknown"));return new Exchange(body,response.headers().firstValue("mcp-session-id").orElse(null));
  }catch(BizException e){throw e;}catch(HttpTimeoutException e){throw new BizException(ErrorCode.CONFLICT,"MCP request timed out");}catch(Exception e){throw new BizException(ErrorCode.CONFLICT,"MCP request failed: "+e.getMessage());}
 }
 private void notifyInitialized(McpServer server,Session session){
  try{URI uri=guard.validate(server.getEndpointUrl());ObjectNode rpc=json.createObjectNode();rpc.put("jsonrpc","2.0");rpc.put("method","notifications/initialized");HttpRequest.Builder b=HttpRequest.newBuilder(uri).timeout(Duration.ofSeconds(10)).header("Content-Type","application/json").header("Accept","application/json, text/event-stream").header("MCP-Protocol-Version",PROTOCOL).POST(HttpRequest.BodyPublishers.ofString(json.writeValueAsString(rpc),StandardCharsets.UTF_8));if(session.id()!=null)b.header("Mcp-Session-Id",session.id());String secret=credentials.resolve(server.getCredentialRef());if(secret!=null)b.header("Authorization","Bearer "+secret);HttpResponse<Void> response=http.send(b.build(),HttpResponse.BodyHandlers.discarding());if(response.statusCode()/100!=2)throw new BizException(ErrorCode.CONFLICT,"MCP initialized notification failed");}catch(BizException e){throw e;}catch(Exception e){throw new BizException(ErrorCode.CONFLICT,"MCP initialized notification failed: "+e.getMessage());}
 }
 private JsonNode parse(HttpResponse<String> response)throws Exception{String type=response.headers().firstValue("content-type").orElse("");String raw=response.body();if(type.contains("text/event-stream")){String last=null;for(String line:raw.split("\\R"))if(line.startsWith("data:"))last=line.substring(5).trim();if(last==null)throw new BizException(ErrorCode.CONFLICT,"MCP SSE response has no data event");return json.readTree(last);}return json.readTree(raw);}
 public record RemoteTool(String name,String description,JsonNode inputSchema,String risk){} public record CallResult(JsonNode result,boolean error){} private record Session(String id){} private record Exchange(JsonNode body,String sessionId){}
}
