package com.hify.mcp.application;
import com.fasterxml.jackson.databind.*; import com.hify.common.*; import com.hify.mcp.api.*; import com.hify.mcp.domain.*; import com.hify.mcp.infrastructure.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.Instant; import java.util.*;
@Service
public class McpRegistryService {
 private final McpServerRepository servers; private final McpToolSnapshotRepository tools; private final McpDebugCallRepository calls; private final McpProtocolClient client; private final McpEndpointGuard guard; private final ObjectMapper json;
 public McpRegistryService(McpServerRepository servers,McpToolSnapshotRepository tools,McpDebugCallRepository calls,McpProtocolClient client,McpEndpointGuard guard,ObjectMapper json){this.servers=servers;this.tools=tools;this.calls=calls;this.client=client;this.guard=guard;this.json=json;}
 @Transactional public String create(McpServerRequest r){guard.validate(r.endpointUrl());if(servers.existsByName(r.name().trim()))throw new BizException(ErrorCode.CONFLICT,"MCP server name already exists");McpServer s=new McpServer(UUID.randomUUID().toString(),r.name().trim(),r.endpointUrl().trim(),blank(r.credentialRef()),r.enabled(),Instant.now());servers.save(s);return s.getId();}
 @Transactional(readOnly=true) public List<McpServerResponse> list(){return servers.findAllByArchivedAtIsNullOrderByCreatedAtDesc().stream().map(this::response).toList();}
 @Transactional(readOnly=true) public McpServerResponse get(String id){return response(server(id));}
 @Transactional public void update(String id,McpServerRequest r){guard.validate(r.endpointUrl());McpServer s=server(id);if(servers.existsByName(r.name().trim())&&!s.getName().equals(r.name().trim()))throw new BizException(ErrorCode.CONFLICT,"MCP server name already exists");s.update(r.name().trim(),r.endpointUrl().trim(),blank(r.credentialRef()),r.enabled());}
 @Transactional public void archive(String id){server(id).archive();}
 @Transactional public List<McpToolResponse> discover(String id){
  McpServer s=server(id);if(!s.isEnabled())throw new BizException(ErrorCode.CONFLICT,"MCP server is disabled");try{List<McpProtocolClient.RemoteTool> found=client.listTools(s);String catalog=found.stream().sorted(Comparator.comparing(McpProtocolClient.RemoteTool::name)).map(t->t.name()+"\n"+canonical(t.inputSchema())+"\n"+t.risk()).reduce("",(a,b)->a+b+"\n"+b);String digest=sha256(catalog);long revision=s.getServerRevision()+1;Instant now=Instant.now();List<McpToolSnapshot> rows=new ArrayList<>();for(var t:found){String schema=canonical(t.inputSchema());rows.add(new McpToolSnapshot(UUID.randomUUID().toString(),s.getId(),revision,t.name(),t.description(),schema,t.risk(),sha256(t.name()+"\n"+schema+"\n"+t.risk()),now));}tools.saveAll(rows);s.discovered(revision,digest);return rows.stream().map(this::toolResponse).toList();}catch(RuntimeException e){s.failed(e.getMessage());throw e;}
 }
 @Transactional(readOnly=true) public List<McpToolResponse> tools(String id){McpServer s=server(id);return tools.findAllByServerIdAndServerRevisionOrderByToolName(id,s.getServerRevision()).stream().map(this::toolResponse).toList();}
 @Transactional public McpDebugResponse debug(String serverId,String toolName,McpDebugRequest request){McpServer s=server(serverId);if(!s.isEnabled()||!"READY".equals(s.getStatus()))throw new BizException(ErrorCode.CONFLICT,"MCP server is not ready");McpToolSnapshot tool=tools.findByServerIdAndServerRevisionAndToolName(serverId,s.getServerRevision(),toolName).orElseThrow(()->new BizException(ErrorCode.NOT_FOUND,"MCP tool not found in current snapshot"));if(!"READ".equals(tool.getRisk()))throw new BizException(ErrorCode.FORBIDDEN,"Only READ MCP tools can be debugged");validateArguments(tool,request.arguments());long started=System.nanoTime();McpProtocolClient.CallResult result=client.call(s,toolName,request.arguments());long elapsed=(System.nanoTime()-started)/1_000_000;String callId=UUID.randomUUID().toString();String resultJson=canonical(result.result());calls.save(new McpDebugCall(callId,serverId,s.getServerRevision(),toolName,tool.getSchemaDigest(),sha256(canonical(request.arguments())),resultJson,result.error(),elapsed,Instant.now()));return new McpDebugResponse(callId,toolName,s.getServerRevision(),tool.getSchemaDigest(),result.result(),result.error(),elapsed);}
 private void validateArguments(McpToolSnapshot tool,JsonNode args){if(args==null||!args.isObject())throw new BizException(ErrorCode.PARAM_ERROR,"MCP tool arguments must be an object");try{JsonNode schema=json.readTree(tool.getInputSchemaJson());for(JsonNode name:schema.path("required"))if(!args.has(name.asText()))throw new BizException(ErrorCode.PARAM_ERROR,"Missing required argument: "+name.asText());Iterator<Map.Entry<String,JsonNode>> it=schema.path("properties").fields();while(it.hasNext()){var p=it.next();if(!args.has(p.getKey()))continue;String type=p.getValue().path("type").asText();JsonNode value=args.get(p.getKey());boolean valid=switch(type){case "string"->value.isTextual();case "integer"->value.isIntegralNumber();case "number"->value.isNumber();case "boolean"->value.isBoolean();case "array"->value.isArray();case "object"->value.isObject();default->true;};if(!valid)throw new BizException(ErrorCode.PARAM_ERROR,"Invalid argument type: "+p.getKey());}}catch(BizException e){throw e;}catch(Exception e){throw new BizException(ErrorCode.INTERNAL_ERROR,"Stored MCP schema is invalid");}}
 private McpServer server(String id){McpServer s=servers.findById(id).orElseThrow(()->new BizException(ErrorCode.NOT_FOUND,"MCP server not found"));if(s.getArchivedAt()!=null)throw new BizException(ErrorCode.NOT_FOUND,"MCP server not found");return s;}
 private McpServerResponse response(McpServer s){return new McpServerResponse(s.getId(),s.getName(),s.getTransport(),s.getEndpointUrl(),s.getCredentialRef(),s.isEnabled(),s.getServerRevision(),s.getSchemaDigest(),s.getStatus(),s.getLastError(),s.getCreatedAt(),s.getUpdatedAt());}
 private McpToolResponse toolResponse(McpToolSnapshot t){try{return new McpToolResponse(t.getToolName(),t.getDescription(),json.readTree(t.getInputSchemaJson()),t.getRisk(),t.getSchemaDigest(),t.getServerRevision());}catch(Exception e){throw new BizException(ErrorCode.INTERNAL_ERROR,"Stored MCP schema is invalid");}}
 private String canonical(JsonNode node){try{return json.writer().writeValueAsString(node);}catch(Exception e){throw new BizException(ErrorCode.INTERNAL_ERROR,"JSON serialization failed");}}
 private String sha256(String text){try{byte[] bytes=MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8));return HexFormat.of().formatHex(bytes);}catch(Exception e){throw new IllegalStateException(e);}}
 private String blank(String value){return value==null||value.isBlank()?null:value.trim();}
}
