package com.hify.runtime;

public enum TerminalReason {
    COMPLETED,
    MAX_TURNS,
    CANCELLED,
    TIMEOUT,
    TOKEN_BUDGET_EXCEEDED,
    TOOL_BUDGET_EXCEEDED,
    RETRY_EXHAUSTED,
    HUMAN_INPUT_REQUIRED,
    PERMISSION_DENIED,
    DUPLICATE_TOOL_CALL,
    CAPABILITY_MISMATCH,
    HISTORY_COMMIT_FAILED,
    MODEL_ERROR,
    FATAL_TOOL_ERROR
}
