CREATE TABLE model_providers (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(64) NOT NULL,
    base_url VARCHAR(2048),
    api_key_env VARCHAR(255),
    default_model VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL
);

CREATE TABLE agent_definitions (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    instructions VARCHAR(8000) NOT NULL,
    provider_id VARCHAR(64) NOT NULL,
    model VARCHAR(255),
    temperature DOUBLE PRECISION NOT NULL,
    max_turns INTEGER NOT NULL,
    enabled_tools VARCHAR(2000),
    enabled BOOLEAN NOT NULL,
    CONSTRAINT fk_agent_provider FOREIGN KEY (provider_id) REFERENCES model_providers(id)
);

CREATE TABLE conversations (
    id VARCHAR(64) PRIMARY KEY,
    agent_id VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_conversation_agent FOREIGN KEY (agent_id) REFERENCES agent_definitions(id)
);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(64) NOT NULL,
    role VARCHAR(32) NOT NULL,
    content VARCHAR(20000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id)
);

CREATE INDEX idx_messages_conversation_created
    ON chat_messages(conversation_id, created_at, id);

CREATE TABLE agent_runs (
    id VARCHAR(64) PRIMARY KEY,
    conversation_id VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    state VARCHAR(32) NOT NULL,
    terminal_reason VARCHAR(64),
    input_message VARCHAR(20000) NOT NULL,
    output_message VARCHAR(20000),
    turns INTEGER NOT NULL,
    tool_calls INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT fk_run_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id),
    CONSTRAINT uq_run_idempotency UNIQUE (conversation_id, idempotency_key)
);

CREATE INDEX idx_runs_conversation_created
    ON agent_runs(conversation_id, created_at);

CREATE INDEX idx_runs_state_updated
    ON agent_runs(state, updated_at);

CREATE TABLE run_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    sequence_no BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    payload VARCHAR(20000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_event_run FOREIGN KEY (run_id) REFERENCES agent_runs(id),
    CONSTRAINT uq_run_event_sequence UNIQUE (run_id, sequence_no)
);

CREATE INDEX idx_events_run_id ON run_events(run_id, id);
