ALTER TABLE agent_runs ADD COLUMN cancel_requested_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE run_checkpoints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    sequence_no BIGINT NOT NULL,
    checkpoint_id VARCHAR(64) NOT NULL,
    turn_no INTEGER NOT NULL,
    tool_calls INTEGER NOT NULL,
    plan_id VARCHAR(64) NOT NULL,
    plan_version INTEGER NOT NULL,
    plan_digest VARCHAR(64) NOT NULL,
    plan_json TEXT NOT NULL,
    messages_json TEXT NOT NULL,
    restorable BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_checkpoint_run FOREIGN KEY (run_id) REFERENCES agent_runs(id),
    CONSTRAINT uq_run_checkpoint_sequence UNIQUE (run_id, sequence_no),
    CONSTRAINT uq_run_checkpoint_id UNIQUE (checkpoint_id)
);

CREATE INDEX idx_checkpoints_run_sequence ON run_checkpoints(run_id, sequence_no DESC);
