CREATE TABLE providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(64) NOT NULL,
    base_url VARCHAR(2048) NOT NULL,
    auth_config TEXT NOT NULL,
    default_model_id VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_provider_public_id UNIQUE (public_id),
    CONSTRAINT uq_provider_name UNIQUE (name)
);

INSERT INTO providers (
    public_id, name, type, base_url, auth_config, default_model_id,
    enabled, created_at, updated_at, deleted
)
SELECT id, name, type, COALESCE(base_url, ''),
       CASE
           WHEN api_key_env IS NULL OR api_key_env = '' THEN '{"version":1}'
           ELSE '{"version":1,"credentialRef":"env:' || api_key_env || '"}'
       END,
       default_model, enabled, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0
FROM model_providers;

CREATE TABLE provider_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    model_id VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    is_default BOOLEAN NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_provider_model_provider FOREIGN KEY (provider_id) REFERENCES providers(id),
    CONSTRAINT uq_provider_model_id UNIQUE (provider_id, model_id)
);

INSERT INTO provider_models (
    provider_id, display_name, model_id, enabled, is_default,
    sort_order, created_at, updated_at, deleted
)
SELECT id, default_model_id, default_model_id, TRUE, TRUE,
       0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0
FROM providers;

CREATE TABLE provider_health (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    latency_ms BIGINT,
    error_code VARCHAR(64),
    message VARCHAR(500),
    checked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_provider_health_provider FOREIGN KEY (provider_id) REFERENCES providers(id),
    CONSTRAINT uq_provider_health_provider UNIQUE (provider_id)
);

INSERT INTO provider_health (
    provider_id, status, created_at, updated_at, deleted
)
SELECT id, 'UNKNOWN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0
FROM providers;

ALTER TABLE agent_definitions DROP CONSTRAINT fk_agent_provider;
ALTER TABLE agent_definitions ADD CONSTRAINT fk_agent_provider_public_id
    FOREIGN KEY (provider_id) REFERENCES providers(public_id);

DROP TABLE model_providers;

CREATE INDEX idx_providers_type_enabled ON providers(type, enabled, deleted);
CREATE INDEX idx_provider_models_provider ON provider_models(provider_id, enabled, sort_order);
CREATE INDEX idx_provider_health_status ON provider_health(status, checked_at);
