ALTER TABLE agent_runs ADD COLUMN capability_revision VARCHAR(64);
ALTER TABLE agent_runs ADD COLUMN tool_schema_digest VARCHAR(64);

CREATE TABLE run_history_commits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    revision BIGINT NOT NULL,
    operation_id VARCHAR(255) NOT NULL,
    semantic_digest VARCHAR(64) NOT NULL,
    messages_json TEXT NOT NULL,
    committed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    projected_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_run_history_run FOREIGN KEY (run_id) REFERENCES agent_runs(id),
    CONSTRAINT uq_run_history_revision UNIQUE (run_id, revision),
    CONSTRAINT uq_run_history_operation UNIQUE (run_id, operation_id)
);

CREATE INDEX idx_run_history_revision ON run_history_commits(run_id, revision);
