import { expect, test } from '@playwright/test'

test('edit prefills, cancels, updates original id, survives reload, then resets for create', async ({ page }) => {
  let server = { id: 'mcp-edit', name: '示例 MCP', endpointUrl: 'https://mcp.example.com/mcp', credentialRef: 'env:OLD_TOKEN', enabled: true, status: 'READY', serverRevision: 3, schemaDigest: 'old-digest' }
  const writes: { method: string; url: string; body: typeof server }[] = []
  await page.route('**/api/v1/mcp-servers**', async route => {
    const request = route.request()
    if (request.method() === 'GET') return route.fulfill({ json: { code: 200, data: [server] } })
    writes.push({ method: request.method(), url: request.url(), body: request.postDataJSON() })
    if (request.method() === 'PUT') server = { ...server, ...request.postDataJSON(), status: 'NEW', schemaDigest: '' }
    return route.fulfill({ json: { code: 200, data: request.method() === 'POST' ? 'new-id' : null } })
  })
  await page.goto('./mcp')
  await page.getByRole('button', { name: '编辑', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '编辑 MCP Server' })
  await expect(dialog.getByLabel('名称', { exact: true })).toHaveValue('示例 MCP')
  await expect(dialog.getByLabel('Endpoint')).toHaveValue(server.endpointUrl)
  await expect(dialog.getByLabel('凭证引用')).toHaveValue('env:OLD_TOKEN')
  await expect(dialog.getByLabel('凭证引用')).toHaveAttribute('type', 'password')
  await dialog.getByLabel('名称', { exact: true }).fill('不保存的修改')
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  expect(writes).toHaveLength(0)
  await page.getByRole('button', { name: '编辑', exact: true }).click()
  await expect(dialog.getByLabel('名称', { exact: true })).toHaveValue('示例 MCP')
  await dialog.getByLabel('名称', { exact: true }).fill('已修改 MCP')
  await dialog.getByLabel('Endpoint').fill('https://new.example.com/mcp')
  await dialog.getByLabel('凭证引用').fill('system:mcp.token')
  await dialog.locator('.el-switch').click()
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByText('已修改 MCP', { exact: true })).toBeVisible()
  expect(writes).toHaveLength(1)
  expect(writes[0].method).toBe('PUT')
  expect(writes[0].url).toMatch(/\/mcp-servers\/mcp-edit$/)
  expect(writes[0].body).toEqual({ name: '已修改 MCP', endpointUrl: 'https://new.example.com/mcp', credentialRef: 'system:mcp.token', enabled: false })
  await expect(page.getByRole('button', { name: '发现工具' })).toBeDisabled()
  await page.reload()
  await expect(page.getByText('已修改 MCP', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '添加 Server' }).click()
  const create = page.getByRole('dialog', { name: '添加 MCP Server' })
  await expect(create.getByLabel('名称', { exact: true })).toHaveValue('')
  await expect(create.getByLabel('凭证引用')).toHaveValue('')
  await expect(create.getByRole('switch')).toBeChecked()
  await create.getByLabel('名称', { exact: true }).fill('新 MCP')
  await create.getByLabel('Endpoint').fill('https://new.example.com/mcp')
  await create.getByRole('button', { name: '保存', exact: true }).click()
  await expect(create).not.toBeVisible()
  expect(writes).toHaveLength(2)
  expect(writes[1].method).toBe('POST')
})

test('edit blocks raw tokens and invalid URLs, retains input on API failure', async ({ page }) => {
  let puts = 0
  await page.route('**/api/v1/mcp-servers**', route => {
    if (route.request().method() === 'GET') return route.fulfill({ json: { code: 200, data: [{ id: 'bad-ref', name: '待修复 MCP', endpointUrl: 'https://mcp.example.com/mcp', credentialRef: 'legacy-raw-test-value', enabled: true, status: 'NEW', serverRevision: 0 }] } })
    puts++
    return route.fulfill({ status: 409, json: { code: 409, message: 'MCP server name already exists' } })
  })
  await page.goto('./mcp')
  await page.getByRole('button', { name: '编辑', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '编辑 MCP Server' })
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog.getByText('仅支持 env:变量名 或 system:属性名，请勿填写 Token 明文')).toBeVisible()
  expect(puts).toBe(0)
  await dialog.getByLabel('凭证引用').fill('env:MCP_TOKEN')
  await dialog.getByLabel('Endpoint').fill('not-a-url')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog.getByText('请输入不含用户名密码的 HTTP(S) 地址')).toBeVisible()
  expect(puts).toBe(0)
  await dialog.getByLabel('Endpoint').fill('https://mcp.example.com/mcp')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByText('MCP server name already exists', { exact: true })).toBeVisible()
  await expect(dialog).toBeVisible()
  await expect(dialog.getByLabel('凭证引用')).toHaveValue('env:MCP_TOKEN')
  await expect(dialog.getByRole('button', { name: '保存', exact: true })).toBeEnabled()
  expect(puts).toBe(1)
})
