<script setup lang="ts">
import { ref } from 'vue'; import { Delete, DocumentAdd, Plus, Search } from '@element-plus/icons-vue'; import type { FormRules } from 'element-plus'; import HifyTable,{type HifyColumn,type HifyPageResult} from '@/components/HifyTable.vue'; import HifyFormDialog from '@/components/HifyFormDialog.vue'; import { archiveDocument,archiveKnowledgeBase,createKnowledgeBase,listDocuments,listKnowledgeBases,testRetrieval,uploadDocument,type KnowledgeBase,type KnowledgeCitation,type KnowledgeDocument } from '@/api/knowledge'; import { notifySuccess } from '@/utils/notify'; import { ElMessageBox } from 'element-plus';
interface Form extends Record<string,unknown>{name:string;description:string;chunkSize:number;chunkOverlap:number;enabled:boolean}
type TableExpose={refresh:(resetPage?:boolean)=>Promise<void>}; type DialogExpose={open:(data?:Partial<Form>)=>Promise<void>}
const table=ref<TableExpose>();const dialog=ref<DialogExpose>();const visible=ref(false);const documentsVisible=ref(false);const current=ref<KnowledgeBase>();const documents=ref<KnowledgeDocument[]>([]);const citations=ref<KnowledgeCitation[]>([]);const retrievalVisible=ref(false);const query=ref('');const fileInput=ref<HTMLInputElement>();const uploading=ref(false)
const columns:HifyColumn<KnowledgeBase>[]=[{label:'知识库',prop:'name',minWidth:180},{label:'文档',prop:'documentCount',width:80},{label:'分块',width:120,slot:'chunk'},{label:'状态',width:90,slot:'status'},{label:'更新时间',prop:'updatedAt',width:190},{label:'操作',width:250,slot:'actions',align:'right'}]
const rules:FormRules<Form>={name:[{required:true,message:'请输入知识库名称',trigger:'blur'}]};const empty=():Form=>({name:'',description:'',chunkSize:600,chunkOverlap:80,enabled:true});const load=(p:{page:number;pageSize:number}):Promise<HifyPageResult<KnowledgeBase>>=>listKnowledgeBases(p)
async function save(model:Form,done:(ok?:boolean)=>void){try{await createKnowledgeBase(model);notifySuccess('知识库已创建');done();await table.value?.refresh(true)}catch{done(false)}}
async function remove(row:KnowledgeBase){await ElMessageBox.confirm(`确认归档「${row.name}」？`,'归档知识库',{type:'warning'});await archiveKnowledgeBase(row.id);notifySuccess('知识库已归档');await table.value?.refresh(true)}
async function openDocuments(row:KnowledgeBase){current.value=row;documentsVisible.value=true;await reloadDocuments()}
async function reloadDocuments(){if(current.value)documents.value=(await listDocuments(current.value.id)).data}
async function selected(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file||!current.value)return;uploading.value=true;try{await uploadDocument(current.value.id,file);notifySuccess('文档已提交索引');await reloadDocuments();await table.value?.refresh()}finally{uploading.value=false;(event.target as HTMLInputElement).value=''}}
async function removeDocument(id:string){await archiveDocument(id);notifySuccess('文档已归档');await reloadDocuments()}
async function retrieve(){if(!current.value||!query.value.trim())return;citations.value=await testRetrieval(current.value.id,query.value.trim())}
function openRetrieval(row:KnowledgeBase){current.value=row;query.value='';citations.value=[];retrievalVisible.value=true}
</script>
<template><section class="page"><div class="page-heading"><div class="page-heading-copy"><span class="eyebrow">GROUNDED KNOWLEDGE</span><h1>知识库</h1><p>管理 canonical 文档、索引状态和带摘要校验的检索引用。</p></div><el-button type="primary" class="primary-gradient" :icon="Plus" @click="dialog?.open()">新建知识库</el-button></div><div class="page-card"><HifyTable ref="table" :columns="columns" :api="load"><template #chunk="{row}"><code>{{row.chunkSize}} / {{row.chunkOverlap}}</code></template><template #status="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'禁用'}}</el-tag></template><template #actions="{row}"><div class="row-actions"><el-button link type="primary" :icon="DocumentAdd" @click="openDocuments(row)">文档</el-button><el-button link type="success" :icon="Search" @click="openRetrieval(row)">检索测试</el-button><el-button link type="danger" :icon="Delete" @click="remove(row)">归档</el-button></div></template></HifyTable></div>
<HifyFormDialog ref="dialog" v-model="visible" title="新建知识库" :rules="rules" :initial-value="empty" @submit="save"><template #default="{model}"><el-form-item label="名称" prop="name"><el-input v-model="model.name" /></el-form-item><el-form-item label="描述"><el-input v-model="model.description" type="textarea" /></el-form-item><el-form-item label="分块大小"><el-input-number v-model="model.chunkSize" :min="64" :max="2048" /></el-form-item><el-form-item label="重叠长度"><el-input-number v-model="model.chunkOverlap" :min="0" :max="model.chunkSize-1" /></el-form-item><el-form-item label="启用"><el-switch v-model="model.enabled" /></el-form-item></template></HifyFormDialog>
<el-drawer v-model="documentsVisible" :title="`${current?.name??''} · 文档`" size="620px"><div class="drawer-tools"><input ref="fileInput" type="file" accept=".txt,.md,text/plain,text/markdown" hidden @change="selected"><el-button type="primary" :loading="uploading" @click="fileInput?.click()">上传 TXT / Markdown</el-button></div><el-table :data="documents" empty-text="暂无文档"><el-table-column prop="name" label="文件" min-width="180"/><el-table-column prop="indexingState" label="索引" width="100"><template #default="{row}"><el-tag :type="row.indexingState==='DONE'?'success':row.indexingState==='FAILED'?'danger':'warning'">{{row.indexingState}}</el-tag></template></el-table-column><el-table-column prop="chunkCount" label="分块" width="70"/><el-table-column label="" width="70"><template #default="{row}"><el-button link type="danger" @click="removeDocument(row.id)">归档</el-button></template></el-table-column></el-table></el-drawer>
<el-dialog v-model="retrievalVisible" title="检索测试" width="720px"><div class="retrieval-bar"><el-input v-model="query" placeholder="输入要验证的问题" @keyup.enter="retrieve"/><el-button type="primary" @click="retrieve">检索</el-button></div><el-empty v-if="!citations.length" description="运行检索后显示 canonical 引用"/><div v-for="item in citations" :key="item.chunkId" class="citation"><strong>#{{item.rank}} · score {{item.score.toFixed(4)}}</strong><p>{{item.content}}</p><code>{{item.digest}}</code></div></el-dialog></section></template>
<style scoped>.row-actions{display:flex;justify-content:flex-end;gap:8px}.row-actions .el-button+.el-button{margin:0}.drawer-tools{display:flex;justify-content:flex-end;margin-bottom:16px}.retrieval-bar{display:flex;gap:10px;margin-bottom:16px}.citation{padding:14px;margin:10px 0;background:var(--color-bg-secondary);border-radius:var(--radius-md)}.citation p{margin:7px 0}.citation code,code{font-size:11px;color:var(--color-text-tertiary)}</style>
