<script setup lang="ts">
import { ref } from 'vue';import { Connection,Delete,Plus,Refresh } from '@element-plus/icons-vue';import type { FormRules } from 'element-plus';import { ElMessageBox } from 'element-plus';import HifyTable,{type HifyColumn,type HifyPageResult} from '@/components/HifyTable.vue';import HifyFormDialog from '@/components/HifyFormDialog.vue';import { archiveMcpServer,callMcpTool,createMcpServer,listMcpServers,listMcpTools,refreshMcpTools,type McpServer,type McpTool } from '@/api/mcp';import { notifySuccess } from '@/utils/notify';
interface Form extends Record<string,unknown>{name:string;endpointUrl:string;credentialRef:string;enabled:boolean}type TableExpose={refresh:(r?:boolean)=>Promise<void>};type DialogExpose={open:()=>Promise<void>}
const table=ref<TableExpose>();const dialog=ref<DialogExpose>();const visible=ref(false);const current=ref<McpServer>();const tools=ref<McpTool[]>([]);const toolsVisible=ref(false);const selectedTool=ref('');const argumentsJson=ref('{}');const resultJson=ref('');const busy=ref('');const columns:HifyColumn<McpServer>[]=[{label:'服务',prop:'name',minWidth:160},{label:'Endpoint',prop:'endpointUrl',minWidth:260},{label:'状态',width:100,slot:'status'},{label:'Revision',prop:'serverRevision',width:90},{label:'Digest',width:130,slot:'digest'},{label:'操作',width:250,slot:'actions',align:'right'}];const rules:FormRules<Form>={name:[{required:true,message:'请输入名称',trigger:'blur'}],endpointUrl:[{required:true,message:'请输入 MCP Endpoint',trigger:'blur'}]};const empty=():Form=>({name:'',endpointUrl:'',credentialRef:'',enabled:true});async function load():Promise<HifyPageResult<McpServer>>{const data=await listMcpServers();return{data,total:data.length,page:1,size:100}}
async function save(f:Form,done:(ok?:boolean)=>void){try{await createMcpServer(f);notifySuccess('MCP Server 已创建');done();await table.value?.refresh(true)}catch{done(false)}}
async function refresh(row:McpServer){busy.value=row.id;try{const found=await refreshMcpTools(row.id);notifySuccess(`发现 ${found.length} 个工具，revision 已更新`);await table.value?.refresh()}finally{busy.value=''}}
async function openTools(row:McpServer){current.value=row;tools.value=await listMcpTools(row.id);selectedTool.value=tools.value.find(t=>t.risk==='READ')?.name??'';argumentsJson.value='{}';resultJson.value='';toolsVisible.value=true}
async function debug(){if(!current.value||!selectedTool.value)return;let args:Record<string,unknown>;try{args=JSON.parse(argumentsJson.value)}catch{await ElMessageBox.alert('参数必须是有效 JSON 对象');return}const result=await callMcpTool(current.value.id,selectedTool.value,args);resultJson.value=JSON.stringify(result,null,2)}
async function remove(row:McpServer){await ElMessageBox.confirm(`确认归档「${row.name}」？`,'归档 MCP Server',{type:'warning'});await archiveMcpServer(row.id);await table.value?.refresh(true)}
</script>
<template><section class="page"><div class="page-heading"><div class="page-heading-copy"><span class="eyebrow">MODEL CONTEXT PROTOCOL</span><h1>MCP Servers</h1><p>发现并冻结工具 schema；控制台只允许调试标注为 READ 的工具。</p></div><el-button type="primary" class="primary-gradient" :icon="Plus" @click="dialog?.open()">添加 Server</el-button></div><div class="page-card"><HifyTable ref="table" :columns="columns" :api="load" :show-pagination="false"><template #status="{row}"><el-tag :type="row.status==='READY'?'success':row.status==='FAILED'?'danger':'info'">{{row.status}}</el-tag></template><template #digest="{row}"><code>{{row.schemaDigest?.slice(0,12)??'—'}}</code></template><template #actions="{row}"><div class="row-actions"><el-button link type="success" :icon="Refresh" :loading="busy===row.id" @click="refresh(row)">发现工具</el-button><el-button link type="primary" :icon="Connection" :disabled="row.status!=='READY'" @click="openTools(row)">工具调试</el-button><el-button link type="danger" :icon="Delete" @click="remove(row)">归档</el-button></div></template></HifyTable></div><HifyFormDialog ref="dialog" v-model="visible" title="添加 MCP Server" :rules="rules" :initial-value="empty" @submit="save"><template #default="{model}"><el-form-item label="名称" prop="name"><el-input v-model="model.name"/></el-form-item><el-form-item label="Endpoint" prop="endpointUrl"><el-input v-model="model.endpointUrl" placeholder="https://mcp.example.com/mcp"/></el-form-item><el-form-item label="凭证引用"><el-input v-model="model.credentialRef" placeholder="env:MCP_TOKEN（不保存明文）"/></el-form-item><el-form-item label="启用"><el-switch v-model="model.enabled"/></el-form-item><div class="warning">生产默认拒绝 loopback、私网和 link-local 地址，并关闭 HTTP 重定向。</div></template></HifyFormDialog>
<el-drawer v-model="toolsVisible" :title="`${current?.name??''} · Tool Inspector`" size="680px"><el-table :data="tools" empty-text="请先执行工具发现"><el-table-column prop="name" label="工具" min-width="160"/><el-table-column prop="description" label="说明" min-width="220"/><el-table-column prop="risk" label="风险" width="100"><template #default="{row}"><el-tag :type="row.risk==='READ'?'success':'warning'">{{row.risk}}</el-tag></template></el-table-column></el-table><div class="debug"><h3>只读调用</h3><el-select v-model="selectedTool" placeholder="选择 READ 工具" style="width:100%"><el-option v-for="tool in tools.filter(t=>t.risk==='READ')" :key="tool.name" :label="tool.name" :value="tool.name"/></el-select><el-input v-model="argumentsJson" type="textarea" :rows="6"/><el-button type="primary" :disabled="!selectedTool" @click="debug">执行 tools/call</el-button><pre v-if="resultJson">{{resultJson}}</pre></div></el-drawer></section></template>
<style scoped>.row-actions{display:flex;justify-content:flex-end;gap:8px}.row-actions .el-button+.el-button{margin:0}code{font-size:11px;color:var(--color-text-tertiary)}.warning{padding:10px 12px;color:var(--color-warning);font-size:12px;background:#fff8e8;border-radius:var(--radius-md)}.debug{display:grid;gap:12px;margin-top:24px}.debug h3{margin:0}.debug pre{overflow:auto;padding:14px;white-space:pre-wrap;background:#10131a;color:#c7f9ef;border-radius:var(--radius-md)}</style>
