<script setup lang="ts">
import { ref } from 'vue'; import { Delete, Plus, Promotion, VideoPlay } from '@element-plus/icons-vue'; import type { FormRules } from 'element-plus'; import { ElMessageBox } from 'element-plus'; import HifyTable,{type HifyColumn,type HifyPageResult} from '@/components/HifyTable.vue'; import HifyFormDialog from '@/components/HifyFormDialog.vue'; import { archiveWorkflow,createWorkflow,listWorkflows,publishWorkflow,runWorkflow,validateWorkflow,type Workflow } from '@/api/workflows'; import { notifySuccess } from '@/utils/notify';
interface Form extends Record<string,unknown>{name:string;description:string;keyword:string;matchedReply:string;defaultReply:string} type TableExpose={refresh:(r?:boolean)=>Promise<void>};type DialogExpose={open:()=>Promise<void>}
const table=ref<TableExpose>();const dialog=ref<DialogExpose>();const visible=ref(false);const busy=ref('');const columns:HifyColumn<Workflow>[]=[{label:'工作流',prop:'name',minWidth:180},{label:'草稿',prop:'draftRevision',width:80},{label:'发布',width:100,slot:'published'},{label:'说明',prop:'description',minWidth:220},{label:'操作',width:250,slot:'actions',align:'right'}];const rules:FormRules<Form>={name:[{required:true,message:'请输入名称',trigger:'blur'}],keyword:[{required:true,message:'请输入分支关键词',trigger:'blur'}]};const empty=():Form=>({name:'',description:'',keyword:'退款',matchedReply:'进入退款流程',defaultReply:'转普通咨询'});const load=(p:{page:number;pageSize:number}):Promise<HifyPageResult<Workflow>>=>listWorkflows(p)
function draft(f:Form){return{name:f.name,description:f.description,schemaVersion:1,nodes:[{nodeKey:'start',type:'START',name:'开始',config:{}},{nodeKey:'route',type:'CONDITION',name:'条件分流',config:{expression:`{{start.userMessage}} contains ${f.keyword}`,outputVariable:'matched'}},{nodeKey:'matched',type:'TEMPLATE',name:'命中回复',config:{template:f.matchedReply,outputVariable:'answer'}},{nodeKey:'other',type:'TEMPLATE',name:'默认回复',config:{template:f.defaultReply,outputVariable:'answer'}},{nodeKey:'endMatched',type:'END',name:'结束',config:{output:'{{matched.answer}}'}},{nodeKey:'endOther',type:'END',name:'结束',config:{output:'{{other.answer}}'}}],edges:[{edgeKey:'e1',sourceNodeKey:'start',targetNodeKey:'route',defaultBranch:false},{edgeKey:'e2',sourceNodeKey:'route',targetNodeKey:'matched',condition:'true',defaultBranch:false},{edgeKey:'e3',sourceNodeKey:'route',targetNodeKey:'other',defaultBranch:true},{edgeKey:'e4',sourceNodeKey:'matched',targetNodeKey:'endMatched',defaultBranch:false},{edgeKey:'e5',sourceNodeKey:'other',targetNodeKey:'endOther',defaultBranch:false}]}}
async function save(f:Form,done:(ok?:boolean)=>void){try{await createWorkflow(draft(f));notifySuccess('工作流草稿已创建');done();await table.value?.refresh(true)}catch{done(false)}}
async function publish(row:Workflow){busy.value=row.id;try{await validateWorkflow(row.id);const v=await publishWorkflow(row.id);notifySuccess(`Workflow v${v.versionNo} 已发布`);await table.value?.refresh()}finally{busy.value=''}}
async function run(row:Workflow){if(!row.publishedVersionId)return;const {value}=await ElMessageBox.prompt('输入本次工作流的 userMessage','运行已发布版本',{inputValue:'我想申请退款'});const result=await runWorkflow(row.publishedVersionId,value);await ElMessageBox.alert(`${result.output??result.errorMessage}\n\n节点数：${result.nodes.length}，耗时：${result.elapsedMs??0} ms`,result.status)}
async function remove(row:Workflow){await ElMessageBox.confirm(`确认归档「${row.name}」？`,'归档工作流',{type:'warning'});await archiveWorkflow(row.id);await table.value?.refresh(true)}
</script>
<template><section class="page"><div class="page-heading"><div class="page-heading-copy"><span class="eyebrow">VERSIONED EXECUTION</span><h1>Workflow</h1><p>校验有向图，发布不可变版本，并查看确定性节点执行轨迹。</p></div><el-button type="primary" class="primary-gradient" :icon="Plus" @click="dialog?.open()">新建工作流</el-button></div><div class="page-card"><HifyTable ref="table" :columns="columns" :api="load"><template #published="{row}"><el-tag :type="row.publishedVersionId?'success':'warning'">{{row.publishedVersionId?'已发布':'未发布'}}</el-tag></template><template #actions="{row}"><div class="row-actions"><el-button link type="success" :icon="Promotion" :loading="busy===row.id" @click="publish(row)">校验并发布</el-button><el-button link type="primary" :icon="VideoPlay" :disabled="!row.publishedVersionId" @click="run(row)">运行</el-button><el-button link type="danger" :icon="Delete" @click="remove(row)">归档</el-button></div></template></HifyTable></div><HifyFormDialog ref="dialog" v-model="visible" title="新建条件分流工作流" :rules="rules" :initial-value="empty" :width="620" @submit="save"><template #default="{model}"><el-form-item label="名称" prop="name"><el-input v-model="model.name"/></el-form-item><el-form-item label="说明"><el-input v-model="model.description"/></el-form-item><el-form-item label="命中关键词" prop="keyword"><el-input v-model="model.keyword"/></el-form-item><el-form-item label="命中回复"><el-input v-model="model.matchedReply"/></el-form-item><el-form-item label="默认回复"><el-input v-model="model.defaultReply"/></el-form-item><div class="hint">控制台生成 START → CONDITION → TEMPLATE → END 双分支图；发布后版本保持不可变。</div></template></HifyFormDialog></section></template>
<style scoped>.row-actions{display:flex;justify-content:flex-end;gap:8px}.row-actions .el-button+.el-button{margin:0}.hint{padding:10px 12px;color:var(--color-text-secondary);font-size:12px;background:var(--color-primary-50);border-radius:var(--radius-md)}</style>
