package com.hify.api;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.hify.application.CommittedHistoryWriter;
import com.hify.application.RunApplicationService;
import com.hify.domain.*;
import com.hify.infra.*;
import com.hify.memory.CanonicalDetailReader;
import com.hify.memory.CanonicalMemoryIndexer;
import com.hify.runtime.*;
import com.hify.runtime.plan.*;
import com.hify.runtime.state.ExecutionContextState;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.util.AopTestUtils;
import org.springframework.test.util.ReflectionTestUtils;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.*;

import static org.assertj.core.api.Assertions.*;

/** Frozen 05ab7a0 bytes are inputs/expected values, never regenerated by the current writer. */
@SpringBootTest
@TestPropertySource(properties = {
        "spring.datasource.url=jdbc:h2:mem:context-authority-goldens;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
        "spring.datasource.username=sa", "spring.datasource.password="
})
class ContextAuthorityGoldenTest {
    private static final Instant CREATED = Instant.parse("2026-10-07T00:00:00Z");
    @Autowired ObjectMapper mapper;
    @Autowired RunApplicationService service;
    @Autowired CommittedHistoryWriter writer;
    @Autowired ConversationRepository conversations;
    @Autowired AgentRunRepository runs;
    @Autowired RunCheckpointRepository checkpoints;
    @Autowired RunHistoryCommitRepository commits;
    @Autowired HistoryDetailRefRepository refs;
    @Autowired CanonicalMemoryIndexer indexer;
    @Autowired CanonicalDetailReader details;
    @Autowired JdbcTemplate db;

    @ParameterizedTest
    @ValueSource(strings = {"plain", "knowledge"})
    void oldCanonicalCheckpointReplayAndReferencesStayReadable(String shape) throws Exception {
        JsonNode bindings = mapper.readTree(golden(shape, "bindings.json"));
        String run = bindings.path("runId").asText();
        String conversation = "golden-conversation-" + shape;
        conversations.saveAndFlush(new Conversation(conversation, "demo-agent", "synthetic golden", CREATED));
        runs.saveAndFlush(new AgentRun(run, conversation, run, "fixture-hash", "合成问题 😀", CREATED));

        String checkpointMessages = golden(shape, "checkpoint-messages.json");
        String checkpointPlan = golden(shape, "checkpoint-plan.json");
        String checkpointContext = golden(shape, "checkpoint-context.json");
        var prefix = messages(checkpointMessages);
        var plan = mapper.readValue(checkpointPlan, ExecutionPlan.class);
        var state = mapper.readValue(checkpointContext, ExecutionContextState.class);
        // Load the OLD fields without going through a new serializer first.
        checkpoints.saveAndFlush(new RunCheckpoint(run, 1, "checkpoint-" + shape, 0, 0,
                plan.id(), plan.version(), plan.digest(), checkpointPlan, state.evidenceVersion(),
                state.gapVersion(), checkpointContext, checkpointMessages, true, CREATED));
        Object target = AopTestUtils.getUltimateTargetObject(service);
        Optional<ExecutionCheckpoint> restored = ReflectionTestUtils.invokeMethod(target, "restoreCheckpoint", run);
        assertThat(restored).contains(new ExecutionCheckpoint("checkpoint-" + shape, 0, 0,
                plan, state, prefix, true, CREATED));
        // A subsequent checkpoint needs a new identity (checkpoint_id has a unique constraint).
        // Preserve the frozen fields; do not ask the production writer to insert the same ID twice.
        var read = restored.orElseThrow();
        var next = new ExecutionCheckpoint("checkpoint-roundtrip-" + shape, read.turn(), read.toolCalls(),
                read.plan(), read.contextState(), read.messages(), read.restorable(), read.createdAt());
        ReflectionTestUtils.invokeMethod(target, "persistCheckpoint", run, next);
        var rewritten = checkpoints.findTopByRunIdOrderBySequenceNoDesc(run).orElseThrow();
        assertThat(rewritten.getSequenceNo()).isEqualTo(2);
        assertThat(rewritten.getMessagesJson()).isEqualTo(checkpointMessages);
        // Map iteration order is not a checkpoint contract; IDs, times, array order and types are.
        assertThat(mapper.readTree(rewritten.getPlanJson())).isEqualTo(mapper.readTree(checkpointPlan));
        assertThat(mapper.readTree(rewritten.getContextJson())).isEqualTo(mapper.readTree(checkpointContext));
        var originalCheckpoint = checkpoints.findAll().stream()
                .filter(row -> row.getRunId().equals(run) && row.getSequenceNo() == 1).findFirst().orElseThrow();
        assertThat(originalCheckpoint.getMessagesJson()).isEqualTo(checkpointMessages);
        assertThat(originalCheckpoint.getPlanJson()).isEqualTo(checkpointPlan);
        assertThat(originalCheckpoint.getContextJson()).isEqualTo(checkpointContext);

        String modelJson = golden(shape, "model-1.json"), toolJson = golden(shape, "tool-1.json");
        String recoveryJson = golden(shape, "tool-1-recovery.json");
        assertThat(sha(modelJson)).isEqualTo(bindings.path("modelDigest").asText());
        assertThat(sha(toolJson)).isEqualTo(bindings.path("toolDigest").asText());
        assertThat(sha(bindings.path("toolDigest").asText() + "\n" + recoveryJson))
                .isEqualTo(bindings.path("recoveryDigest").asText());
        commits.saveAndFlush(new RunHistoryCommit(run, 1, "model:1",
                bindings.path("modelDigest").asText(), modelJson, CREATED));
        var oldTool = new RunHistoryCommit(run, 2, "tool:golden-call",
                bindings.path("toolDigest").asText(), toolJson, CREATED);
        oldTool.bindRecovery(recoveryJson, bindings.path("recoveryDigest").asText());
        commits.saveAndFlush(oldTool);
        var modelMessages = messages(modelJson);
        var toolMessages = messages(toolJson);
        var recovery = mapper.readValue(recoveryJson, HistoryCommitter.ToolReplay.class);
        var port = writer.forRun(run);
        assertThat(port.replay("model:1", prefix).orElseThrow().message())
                .isEqualTo(modelMessages.get(modelMessages.size() - 1));
        var toolReplay = port.replay("tool:golden-call", modelMessages).orElseThrow();
        assertThat(toolReplay.message()).isEqualTo(toolMessages.get(toolMessages.size() - 1));
        assertThat(toolReplay.tool()).isEqualTo(recovery);
        assertThat(toolReplay.message().toolCallId()).isEqualTo("golden-call");

        // Seed the old det_ identities, not current factory output. Reader must resolve each old ID.
        for (JsonNode binding : bindings.path("details")) {
            String canonical = golden(shape, binding.path("file").asText());
            assertThat(sha(canonical)).isEqualTo(binding.path("contentDigest").asText());
            var message = mapper.readValue(canonical, RuntimeMessage.class);
            refs.saveAndFlush(new HistoryDetailRef(binding.path("id").asText(), run, conversation,
                    binding.path("sourceRevision").asLong(), binding.path("sourceMessageIndex").asInt(),
                    DetailRefKind.valueOf(binding.path("kind").asText()), message.role(),
                    binding.path("contentDigest").asText(), "synthetic", "synthetic", "", "", 1,
                    CREATED, CREATED));
            assertThat(details.read(binding.path("id").asText()).canonicalJson()).isEqualTo(canonical);
        }
        assertThat(port.commit("model:1", modelMessages).replayed()).isTrue();
        assertThat(port.commitTool("tool:golden-call", toolMessages, recovery).replayed()).isTrue();
        // Assert the indexer itself, since CommittedHistoryWriter deliberately swallows index errors.
        var indexed = indexer.index(run, 2, toolMessages, CREATED);
        assertThat(indexed).hasSize(shape.equals("plain") ? 4 : 0);
        assertThat(refs.findByRunIdOrderBySourceMessageIndexAsc(run)).hasSize(indexed.size());
        for (int i = 0; i < indexed.size(); i++) {
            JsonNode binding = bindings.path("details").get(i);
            assertThat(indexed.get(i).getId()).isEqualTo(binding.path("id").asText());
            assertThat(indexed.get(i).getSourceRevision()).isEqualTo(binding.path("sourceRevision").asLong());
            assertThat(details.read(indexed.get(i).getId()).canonicalJson())
                    .isEqualTo(golden(shape, binding.path("file").asText()));
        }
        var storedModel = commits.findByRunIdAndOperationId(run, "model:1").orElseThrow();
        var storedTool = commits.findByRunIdAndOperationId(run, "tool:golden-call").orElseThrow();
        assertThat(storedModel.getMessagesJson()).isEqualTo(modelJson);
        assertThat(storedModel.getSemanticDigest()).isEqualTo(bindings.path("modelDigest").asText());
        assertThat(storedTool.getMessagesJson()).isEqualTo(toolJson);
        assertThat(storedTool.getSemanticDigest()).isEqualTo(bindings.path("toolDigest").asText());
        assertThat(storedTool.getRecoveryJson()).isEqualTo(recoveryJson);
        assertThat(storedTool.getRecoveryDigest()).isEqualTo(bindings.path("recoveryDigest").asText());

        if (shape.equals("knowledge")) {
            // This fixture proves old assembly/shape, not that the synthetic source was published.
            var citation = mapper.readValue(golden(shape, "citation-input.json"),
                    com.hify.knowledge.api.KnowledgeCitation.class);
            String assembled = ReflectionTestUtils.invokeMethod(target, "knowledgeContext", List.of(citation));
            assertThat(assembled).isEqualTo(prefix.get(1).content());
            assertThat(prefix.get(1).role()).isEqualTo("system");
        }

        // Contrasts: matching old bytes succeed; altered prefix/content/recovery do not.
        var changedPrefix = new ArrayList<>(prefix);
        changedPrefix.set(0, RuntimeMessage.system("not the frozen policy"));
        assertThatThrownBy(() -> port.replay("model:1", changedPrefix))
                .isInstanceOf(HistoryReplayException.class).hasMessageContaining("prefix");
        db.update("update run_history_commits set recovery_json='{}' where run_id=? and operation_id=?",
                run, "tool:golden-call");
        assertThatThrownBy(() -> port.replay("tool:golden-call", modelMessages))
                .isInstanceOf(HistoryReplayException.class).hasMessageContaining("digest");
        db.update("update run_history_commits set messages_json='[]' where run_id=? and operation_id='model:1'", run);
        assertThatThrownBy(() -> port.replay("model:1", prefix))
                .isInstanceOf(HistoryReplayException.class).hasMessageContaining("digest");
        if (shape.equals("plain")) {
            assertThatThrownBy(() -> details.read(bindings.path("details").get(0).path("id").asText()))
                    .isInstanceOf(IllegalStateException.class).hasMessageContaining("outside");
        }
    }

    private List<RuntimeMessage> messages(String json) throws Exception {
        return mapper.readValue(json, new TypeReference<>() {});
    }

    private String golden(String shape, String file) throws Exception {
        try (var input = Objects.requireNonNull(getClass().getResourceAsStream(
                "/context-authority-05ab7a0/" + shape + "/" + file), "Frozen golden missing: " + file)) {
            return new String(input.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    private static String sha(String value) throws Exception {
        return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256")
                .digest(value.getBytes(StandardCharsets.UTF_8)));
    }
}
